try:
    print(x)
except:
    print("an exception")
#try:allow yo test block of code
#except:let you handle error